### ISSUE TITLE
Crashing During Fête: Shear-a-Yak

### ISSUE THREAD

**Issue by SomebodyAnxious** [InitialDet/AutoHook#127] opened 2023-10-21 03:58 UTC
This bug is oddly specific, but after a lot of testing, I found that this plugin was the source of a crash after every attempt at Shear-a-Yak.

I have no idea why.

**Comment by InitialDet** [comment] 2023-10-21 05:51
Now that is weird, the plugin literally does nothing outside of fishing, no processing at all. Did you check dalamud.log and see what was the crash error?

**Comment by SomebodyAnxious** [comment] 2023-10-21 06:16
Yes, but it wasn't any help. So I just turned off plugins until I stopped crashing and then AutoHook ended up being the problem.

**Comment by InitialDet** [comment] 2023-10-21 06:29
Well ill try and see for myself, but im certain it was another plugin conflicting with something. Because like i said before, autohook does nothing outside of fishing to even have a "chance" to crash the game.

**Comment by InitialDet** [comment] 2023-10-21 06:30
If you happen to crash again, please send me the log files

**Comment by cheese-demon** [comment] 2023-11-29 02:40
I'm not OP but have been crashing the moment I press the button for Aetheromatic Clipper in Shear-a-Yak. Got pointed to this issue from a forum thread. I usually got nothing in the logs but I decided to hook up the VS debugger to see what the crash looks like and sure enough
![image](https://github.com/InitialDet/AutoHook/assets/25679288/bebf8a88-f3b7-4fcf-9a30-05a0a299e876)

```
2023-11-28 18:11:28.720 -08:00 [FTL] Unhandled exception on AppDomain
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoHook.HookingManager.OnUseAction(IntPtr manager, ActionType actionType, UInt32 actionId, GameObjectID targetId, UInt32 a4, UInt32 a5, UInt32 a6, IntPtr a7)
   at SimpleTweaksPlugin.Tweaks.SanctuarySprintReplacer.UseActionDetour(ActionManager* mgr, ActionType type, UInt32 id, Int64 targetid, Int32 a4, Int32 a5, Int32 a6, Void* a7) in /work/repo/Tweaks/SanctuarySprintReplacer.cs:line 53
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 433
```
Looks like it might be an interaction with SimpleTweaks, I'm not sure; I'll try it again when I can. It's annoying to figure out because the fete is up for like 5 minutes every 2 hours and crashing takes most of that time to get back in, I can only try one thing because loading back puts you in the Pillars.
Anyway here's the log.
[dalamud.log](https://github.com/InitialDet/AutoHook/files/13495481/dalamud.log)

**Comment by cheese-demon** [comment] 2023-11-29 07:01
Turned off AutoHook, left that SimpleTweak enabled - no crash. 
Turned off the tweak, enabled AutoHook, and it crashed again with a different second hook listed. 

```
2023-11-28 22:12:22.482 -08:00 [FTL] Unhandled exception on AppDomain
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoHook.HookingManager.OnUseAction(IntPtr manager, ActionType actionType, UInt32 actionId, GameObjectID targetId, UInt32 a4, UInt32 a5, UInt32 a6, IntPtr a7)
   at CrossUp.Game.Hooks.ActionBarHooks.ActionBarReceiveEventDetour(AddonActionBarBase* barBase, UInt32 eventType, Void* a3, Void* a4, NumberArrayData** numberArrayData) in /work/repo/Game/Hooks/ActionBar.cs:line 96
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 433
```

**Comment by cekefun** [comment] 2023-11-29 13:20
I can confirm this crash. Sadly, I don't get an error message on the crash. 
If Autohook is the only mod turned on, it crashes. Even if autohook is toggled off through /ahoff, it crashes.

**Comment by cekefun** [comment] 2023-11-29 13:31
Maybe it has something to do with that special tool that gets used that somehow gets recognized as a fishing pole?

**Comment by cheese-demon** [comment] 2023-11-29 14:30
Ok, here we go. Removed every other plugin, enabled managed exception handling, and 
![image](https://github.com/InitialDet/AutoHook/assets/25679288/0f2d558c-444e-4161-9b42-f024dfc0536a)
`actionType` is `ActionType.Action` and `actionId` is 24280 as expected so that should mean that the issue is with `PlayerResources.ActionTypeAvailable()`? VS isn't decompiling that symbol so I'll have to actually build the plugin and wait for 1-2 days for fetes to come around again to look deeper.

**Comment by cekefun** [comment] 2023-11-29 15:15
Maybe before anyone tries it, the aether thingy in Diadem DOES work. It seems to be coded differently even though it seems to be using the exact same animation.

**Comment by InitialDet** [comment] 2023-11-29 15:57
Some context for anyone curious about this issue.

When making the plugin i needed to find a way to know when the user started fishing or mooching without needing to check for the text displayed in the chat. My solution was to check if the player used the actions Cast (id 289) or Mooch 1/2 (ids: 297/268) and call OnBeganFishing or OnBeganMooch to set everything up.

The problem was, if the user pressed Cast or Mooch even when the action was not available (when the icon is dark, like trying to use Cast while already fishing), the game would still recognized the press as the action being used and OnBeganFishing/OnBeganMooch were being called in the wrong time and everything bugged out.

The solution for that was checking if the pressed action is actually AVAILABLE and OFF COOLDOWN (for mooch2), its a simple check and worked pretty well.

Well, now for reasons i dont even think its worth the effort to find out why, checking if Aetheromatic Clipper (id: 24280) is available and off cooldown makes the game crash?? Most actions return a simple true or false but this one is being a lil different.

I'll make sure the plugin only checks fishing related actions and the problem should fixed

**Comment by InitialDet** [comment] 2023-12-06 03:28
Should be fixed

**Closed by InitialDet** 2023-12-06 03:28 UTC
