### ISSUE TITLE
Watered-Cordial doesn't work after selected "Change Priority" option on "Cordial" 

### ISSUE THREAD

**Issue by Sparria** [InitialDet/AutoHook#124] opened 2023-10-18 10:26 UTC
Bug maybe? able to get it work prior to the major rework.
![image](https://github.com/InitialDet/AutoHook/assets/42709626/38e89adb-1e19-4d28-8d9d-efa42b8deffa)
![image](https://github.com/InitialDet/AutoHook/assets/42709626/17ad8570-27e9-4888-8c36-7506075911da)

**Comment by InitialDet** [comment] 2023-10-18 11:27
Now thats weird, can you tell me what types of cordials you currently have on your inventory? like if you only have watered cordials or any other type too

The "works on my machine" type of bugs makes me go crazy lol

**Comment by InitialDet** [comment] 2023-10-18 12:43
Well i found some possible causes for it but let me know if it still happening

**Comment by Constmar** [comment] 2023-10-18 21:14
Cordial doesn't get used for me either, and it used to before the rework all the time, got 400 Hq Cordials, mine doesn't even try to use it, tried with both boxes checked/unchecked

**Comment by InitialDet** [comment] 2023-10-18 21:20
> Cordial doesn't get used for me either, and it used to before the rework all the time, got 400 Hq Cordials, mine doesn't even try to use it, tried with both boxes checked/unchecked

Do you still have this problem in the 3.0.0.5 version?

**Comment by Constmar** [comment] 2023-10-18 21:24
Yes, right now live tried on Circuit Tilapia, one of the new fishies

**Comment by InitialDet** [comment] 2023-10-18 21:36
> Yes, right now live tried on Circuit Tilapia, one of the new fishies

Did you have your saddlebag open? Im trying to reproduce here and thats the only condition it doesnt use cordials

**Comment by Constmar** [comment] 2023-10-18 21:38
nope, nothing opened, just the ah config window and gatherbuddy, xllog doesn't show any errors

**Comment by InitialDet** [comment] 2023-10-18 22:16
3.0.0.6 should be up in few minutes with a change in the way cordials are used, let me know if it works now.

**Comment by Constmar** [comment] 2023-10-18 22:50
nope, still nothing, all the other skills seem to work

**Comment by InitialDet** [comment] 2023-10-18 23:02
Would you mind recording a video for me with the plugin console open?

**Comment by InitialDet** [comment] 2023-10-18 23:10
Wait i think i know what it might be, gimme a minute

**Comment by InitialDet** [comment] 2023-10-18 23:24
3.0.0.7 should be up soon, this time for sure
![image](https://github.com/InitialDet/AutoHook/assets/13919114/302b9f27-9838-401c-95bc-993bb9fa0e0a)

**Comment by Constmar** [comment] 2023-10-18 23:28
HEEEY! you fixed it! thank you so so so much! 💌

**Comment by Constmar** [comment] 2023-10-18 23:30
> Would you mind recording a video for me with the plugin console open? you can enable it in the config tab

there was nothing there, i looked myself or in xl log, 

![image](https://github.com/InitialDet/AutoHook/assets/122679192/88893d98-775c-4bf7-9882-6be41cbc8677)

this is new!

**Comment by InitialDet** [comment] 2023-10-18 23:40
> HEEEY! you fixed it! thank you so so so much! 💌

LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

> this is new!

Yeah... it was just trying to use Normal Quality Cordial instead of the HQ ones, so the cast got blocked because you probably didnt have any NQ in your inventory.

**Comment by InitialDet** [comment] 2023-10-18 23:42
Anyway thanks for the report guys, i'm closing this issue since it should be fixed now. Feel free to reopen if somehow its still broken

**Closed by InitialDet** 2023-10-18 23:42 UTC

**Comment by Constmar** [comment] 2023-10-18 23:57
> > HEEEY! you fixed it! thank you so so so much! 💌
> 
> LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> 
> > this is new!
> 
> Yeah... it was just trying to use Normal Quality Cordial instead of the HQ ones, so the cast got blocked because you probably didnt have any NQ in your inventory.

that is correct, i didn't, thank you again!
